### ISSUE TITLE
submitting index job through the webform fails on some setups

### ISSUE THREAD

**Issue by bradfordcondon** [statonlab/tripal_cv_xray#24]
For whatever reason, this issue persists on my site, even after reinstalling to get queues set up.

```
LINE 7: ...3339', '3357', '3370', '3384')) AND (DB.name IN  ()) AND (DB...
                                                             ^ in /Users/chet/UTK/tripal/includes/database/database.inc:2227
Stack trace:
#0 /Users/chet/UTK/tripal/includes/database/database.inc(2227): PDOStatement->execute(Array)
#1 /Users/chet/UTK/tripal/includes/database/pgsql/database.inc(111): DatabaseStatementBase->execute(Array, Array)
#2 /Users/chet/UTK/tripal/includes/database/select.inc(1280): DatabaseConnection_pgsql->query('SELECT CT.featu...', Array, Array)
#3 /Users/chet/UTK/tripal/sites/all/modules/custom/tripal_cv_xray/includes/Jobs/XRayIndexerJob.php(253): SelectQuery->execute()
#4 /Users/chet/UTK/tripal/sites/all/modules/custom/tripal_cv_xray/includes/Jobs/XRayIndexerJob.php(161): XRayIndexerJob->loadCVTerms('feature',
Array)
#5 /Users/chet/UTK/tripal/sites/all/modules/custom/tripal_cv_xray/includes/Jobs/XRayIndexerJob.php(98): XRayIndexerJob->loadData(Array)
#6 /Users/chet/UTK/tripal/sites/all/modules/custom/tripal_cv_xray/includes/Jobs/XRayQueue.php(14): XRayIndexerJob->handle()
#7 /Users/chet/UTK/tripal/sites/all/modules/ultimate_cron/plugins/ultimate_cron/settings/queue.class.php(118):
XRayQueue::run(Object(XRayIndexerJob))
#8 /Users/chet/UTK/tripal/sites/all/modules/ultimate_cron/ultimate_cron.job.inc(332):
UltimateCronQueueSettings::worker_callback(Object(UltimateCronJob), Array)
#9 /Users/chet/UTK/tripal/sites/all/modules/ultimate_cron/ultimate_cron.plugin.inc(1005): UltimateCronJob->invoke()
#10 /Users/chet/UTK/tripal/sites/all/modules/ultimate_cron/ultimate_cron.job.inc(479): UltimateCronLauncher->run(Object(UltimateCronJob))
#11 /Users/chet/UTK/tripal/sites/all/modules/ultimate_cron/plugins/ultimate_cron/launcher/serial.class.php(226): UltimateCronJob->run()
#12 /Users/chet/UTK/tripal/sites/all/modules/ultimate_cron/ultimate_cron.job.inc(399): UltimateCronSerialLauncher->launch(Object(UltimateCronJob))
#13 /Users/chet/UTK/tripal/sites/all/modules/ultimate_cron/plugins/ultimate_cron/launcher/serial.class.php(360): UltimateCronJob->launch()
#14 /Users/chet/UTK/tripal/sites/all/modules/ultimate_cron/plugins/ultimate_cron/launcher/serial.class.php(328):
UltimateCronSerialLauncher->runThread('1', 1, Array)
#15 /Users/chet/UTK/tripal/sites/all/modules/ultimate_cron/ultimate_cron.module(1650): UltimateCronSerialLauncher->launchJobs(Array)
#16 /Users/chet/UTK/tripal/sites/all/modules/ultimate_cron/ultimate_cron.module(1626): ultimate_cron_run_launchers()
#17 /Users/chet/UTK/tripal/sites/all/modules/ultimate_cron/ultimate_cron.drush.inc(427): ultimate_cron_run_scheduled(false)
#18 phar:///usr/local/bin/drush/includes/command.inc(199): drush_ultimate_cron_cron_run()
#19 phar:///usr/local/bin/drush/lib/Drush/Boot/BaseBoot.php(67): drush_dispatch(Array)
#20 phar:///usr/local/bin/drush/includes/preflight.inc(66): Drush\Boot\BaseBoot->bootstrap_and_dispatch()
#21 phar:///usr/local/bin/drush/includes/startup.inc(458): drush_main()
#22 phar:///usr/local/bin/drush/includes/startup.inc(365): drush_run_main(false, '/', 'Phar detected. ...')
#23 phar:///usr/local/bin/drush/drush(114): drush_startup(Array)
#24 /usr/local/bin/drush(10): require('phar:///usr/loc...')
#25 {main}
Invalid argument supplied for foreach() query.inc:1853                                                                                            [warning]
WD tripal_cv_xray: SQLSTATE[42601]: Syntax error: 7 ERROR:  syntax error at or near ")"                                                           [error]
LINE 7: ...0', '17151', '17152', '17153')) AND (DB.name IN  ()) AND (DB...
                                                             ^
WD tripal_cv_xray: Queue item 463 from queue tripal_cv_xray failed with message PDOException: SQLSTATE[42601]: Syntax error: 7 ERROR:  syntax     [error]
error at or near ")"
LINE 7: ...0', '17151', '17152', '17153')) AND (DB.name IN  ()) AND (DB...
                                                             ^ in /Users/chet/UTK/tripal/includes/database/database.inc:2227
Stack trace:
#0 /Users/chet/UTK/tripal/includes/database/database.inc(2227): PDOStatement->execute(Array)
#1 /Users/chet/UTK/tripal/includes/database/pgsql/database.inc(111): DatabaseStatementBase->execute(Array, Array)
#2 /Users/chet/UTK/tripal/includes/database/select.inc(1280): DatabaseConnection_pgsql->query('SELECT CT.featu...', Array, Array)
#3 /Users/chet/UTK/tripal/sites/all/modules/custom/tripal_cv_xray/includes/Jobs/XRayIndexerJob.php(253): SelectQuery->execute()
#4 /Users/chet/UTK/tripal/sites/all/modules/custom/tripal_cv_xray/includes/Jobs/XRayIndexerJob.php(161): XRayIndexerJob->loadCVTerms('feature',
Array)
#5 /Users/chet/UTK/tripal/sites/all/modules/custom/tripal_cv_xray/includes/Jobs/XRayIndexerJob.php(98): XRayIndexerJob->loadData(Array)
#6 /Users/chet/UTK/tripal/sites/all/modules/custom/tripal_cv_xray/includes/Jobs/XRayQueue.php(14): XRayIndexerJob->handle()
#7 /Users/chet/UTK/tripal/sites/all/modules/ultimate_cron/plugins/ultimate_cron/settings/queue.class.php(118):
XRayQueue::run(Object(XRayIndexerJob))
#8 /Users/chet/UTK/tripal/sites/all/modules/ultimate_cron/ultimate_cron.job.inc(332):
UltimateCronQueueSettings::worker_callback(Object(UltimateCronJob), Array)
#9 /Users/chet/UTK/tripal/sites/all/modules/ultimate_cron/ultimate_cron.plugin.inc(1005): UltimateCronJob->invoke()
#10 /Users/chet/UTK/tripal/sites/all/modules/ultimate_cron/ultimate_cron.job.inc(479): UltimateCronLauncher->run(Object(UltimateCronJob))
#11 /Users/chet/UTK/tripal/sites/all/modules/ultimate_cron/plugins/ultimate_cron/launcher/serial.class.php(226): UltimateCronJob->run()
#12 /Users/chet/UTK/tripal/sites/all/modules/ultimate_cron/ultimate_cron.job.inc(399): UltimateCronSerialLauncher->launch(Object(UltimateCronJob))
#13 /Users/chet/UTK/tripal/sites/all/modules/ultimate_cron/plugins/ultimate_cron/launcher/serial.class.php(360): UltimateCronJob->launch()
#14 /Users/chet/UTK/tripal/sites/all/modules/ultimate_cron/plugins/ultimate_cron/launcher/serial.class.php(328):
UltimateCronSerialLauncher->runThread('1', 1, Array)
#15 /Users/chet/UTK/tripal/sites/all/modules/ultimate_cron/ultimate_cron.module(1650): UltimateCronSerialLauncher->launchJobs(Array)
#16 /Users/chet/UTK/tripal/sites/all/modules/ultimate_cron/ultimate_cron.module(1626): ultimate_cron_run_launchers()
#17 /Users/chet/UTK/tripal/sites/all/modules/ultimate_cron/ultimate_cron.drush.inc(427): ultimate_cron_run_scheduled(false)
#18 phar:///usr/local/bin/drush/includes/command.inc(199): drush_ultimate_cron_cron_run()
#19 phar:///usr/local/bin/drush/lib/Drush/Boot/BaseBoot.php(67): drush_dispatch(Array)
#20 phar:///usr/local/bin/drush/includes/preflight.inc(66): Drush\Boot\BaseBoot->bootstrap_and_dispatch()
#21 phar:///usr/local/bin/drush/includes/startup.inc(458): drush_main()
#22 phar:///usr/local/bin/drush/includes/startup.inc(365): drush_run_main(false, '/', 'Phar detected. ...')
#23 phar:///usr/local/bin/drush/drush(114): drush_startup(Array)
#24 /usr/local/bin/drush(10): require('phar:///usr/loc...')
#25 {main}
```

**Comment by almasaeed2010** [comment]
Has this been fixed?
